/**
 * cPanel Standalone Server for Next.js (Ratimutsa Farm)
 * This script bootstraps the Next.js standalone server for cPanel Passenger.
 *
 * It assumes a 'standalone' build was generated with `output: 'standalone'` in next.config.js
 * and that all static assets (.next/static and public) have been copied correctly.
 */

process.env.NODE_ENV = 'production';

// cPanel Passenger provides PORT as an environment variable
const port = process.env.PORT || 3000;
process.env.PORT = String(port);
process.env.HOSTNAME = '0.0.0.0';

console.log(`Starting Ratimutsa Production Server on port ${port}...`);

try {
  // Load the standalone server generated by Next.js build
  // When extracted on cPanel, both this file and Next.js's server.js will be in the same root
  const standaloneServerPath = './server.js';
  
  if (require('fs').existsSync(standaloneServerPath)) {
    require(standaloneServerPath);
  } else {
    console.error('Error: Standalone server not found at ' + standaloneServerPath);
    console.error('Make sure you have run "npm run build" and the .next/standalone directory exists.');
    process.exit(1);
  }
} catch (error) {
  console.error('Failed to start Next.js standalone server:', error);
  process.exit(1);
}
